### ISSUE TITLE
2017 JASPAR DB

### ISSUE THREAD

**Issue by akhst7** [ge11232002/TFBSTools#11]
Is there any way to import 2017 JAPSAR DB as a getmatrixset object ?

**Comment by ge11232002** [comment]
You mean JASPAR2016? You can load all the matrices by 
```R
getMatrixSet(JASPAR2016, opts=list(all=TRUE)
```

**Comment by akhst7** [comment]
No. I have Jaspar 2016.  I saw  an update version (2017) of Japspar DB on the Jaspar web site and was wondering if I could update the 2016 DB somehow. 

Thanks. 

AKi

**Comment by ge11232002** [comment]
There is no JASPAR 2017 yet. I am not sure where you see this.

**Comment by akhst7** [comment]
My apologies.  When I saw a 2017 core db file (dated 3-16), I thought it was the version updated from the 2016 db.  

One quick question. How does TFSBtools compare to DeepBind ?  

Thanks. 

Aki

**Comment by ge11232002** [comment]
We didn't systematically compare with DeepBind. TFBSTools stands a conventional way of predicting putative binding sites.
