### ISSUE TITLE
Interpretation of the score

### ISSUE THREAD

**Issue by akhst7** [ge11232002/TFBSTools#15]
Hi, 

I am probably missing info regarding the interpretation of the score but what are the difference between negative vs positive values ? 

Thanks.

**Comment by ge11232002** [comment]
The sign of the score doesn't mean anything directly. The score is the absolute score of a binding site. For different PWM, the maximal score and minimal score can vary a lot.
How to calculate the score is described in 
Wasserman, W. W., & Sandelin, A. (2004). Applied bioinformatics
     for the identification of regulatory elements. Nature Publishing
     Group, 5(4), 276-287. doi:10.1038/nrg1315

During the scanning, teh relative score is used for measuring binding affinity.

**Comment by akhst7** [comment]
So greater the score regardless of + or -, the better chances of TF binding to its binding site ?

**Comment by ge11232002** [comment]
A larger score, a higher chance. For a given PWM, 3 is larger than -2. -1 is also larger than -2.

**Comment by akhst7** [comment]
So let me get this straight.  In the following table, the seq #5 has the highest chance of TF binding ? 

         seqname source feature start  end      score strand frame
1  hFBXO3promter   TFBS    TFBS   117  127 -5.8066256      +     .
2  hFBXO3promter   TFBS    TFBS   126  136 -2.2885383      +     .
3  hFBXO3promter   TFBS    TFBS   140  150 -2.5414364      +     .
4  hFBXO3promter   TFBS    TFBS   189  199 -6.8638992      +     .
5  hFBXO3promter   TFBS    TFBS   298  308  0.3123223      +     .
6  hFBXO3promter   TFBS    TFBS   543  553 -5.6919816      +     .
7  hFBXO3promter   TFBS    TFBS   693  703 -1.4604457      +     .
8  hFBXO3promter   TFBS    TFBS  1204 1214  1.6100509      +     .
9  hFBXO3promter   TFBS    TFBS   260  270 -3.1280705      -     .
10 hFBXO3promter   TFBS    TFBS   296  306 -4.1434770      -     .
11 hFBXO3promter   TFBS    TFBS   786  796 -0.2857262      -     .
12 hFBXO3promter   TFBS    TFBS   862  872 -4.8864631      -     .
13 hFBXO3promter   TFBS    TFBS  1010 1020 -6.8369965      -     .

**Comment by ge11232002** [comment]
No. # 8 has higher score pf 1.61.

**Comment by akhst7** [comment]
Ok I missed it.  Thanks.
