### ISSUE TITLE
ParseMEMEOutput Cannot Read My MEME Output File

### ISSUE THREAD

**Issue by VikramMisra** [ge11232002/TFBSTools#16]
Hello,

I am running R 3.4.3 on macOS High Sierra 10.13.3 .

I am trying to run "parseMEMEOutput", but I get the following message:

> Error in seq.default(from = indexNames[i] + 4, to = indexNames[i] + 4 +  : 
  'to' must be a finite number

Here is the file:
[meme.txt](https://github.com/ge11232002/TFBSTools/files/1862464/meme.txt)

I would greatly appreciate your help in resolving this issue.

Thank you very much,
Vikram Misra

**Comment by ge11232002** [comment]
Hi, I am aware of changed output format from newer version of MEME. Can you please install the github version via
```R
devtools::install_github("ge11232002/TFBSTools")
```

So these fixes will be merged into Bioconductor release.
