### ISSUE TITLE
PFM question

### ISSUE THREAD

**Issue by erin-a-clark** [ge11232002/TFBSTools#19]
Hi,

I'm trying to work with PFMs that I've downloaded from cisBP, but when I run
`toPWM(pfm, pseudocounts=0.08)`

The resulting PWM is a matrix of 0's. e.g...
Matrix: 
  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
A    0    0    0    0    0    0    0    0    0
C    0    0    0    0    0    0    0    0    0
G    0    0    0    0    0    0    0    0    0
T    0    0    0    0    0    0    0    0    0

I'm guessing this is because the cisBP matrix is in fractions so the PFM looks like...
A [   0.05   0.001   0.001   0.001   0.001   0.001   0.769   0.001   ]
C [   0.583   0.001   0.001   0.117   0.001   0.001   0.175   0.897   ]
G [   0.184   0.001   0.997   0.001   0.001   0.183   0.001   0.001   ]
T [   0.184   0.997   0.001   0.881   0.997   0.815   0.055   0.101   ]

instead of...
A  [   468    127     87      0      0      0      0      0   1871      0   1072 ]
C  [   277   1279   1406      0      0      0      0      0    157   2007    573 ]
G  [   478    752    209      0   2490      0      0    287      0      0     71 ]
T  [  1267    332    788   2490      0   2490   2490   2203    462    483    774 ]

Is it possible to use the type of PFM from cisBP to make a PWM with TFBSTools?

Thank you for your help!

**Comment by ge11232002** [comment]
Hi,

When you have the matrix with fractions inside, you can convert the log scaled PWM with
```R
# p is the matrix of fraction.
# bg is the background frequency. For instance, bg=c(A=0.25, C=0.25, G=0.25, T=0.25)
pwm <- log2(sweep(p, MARGIN=1, bg, "/")
# To get the PWMatrix object
PWMatrix(profileMatrix=pwm)
```

**Comment by erin-a-clark** [comment]
Hi,

Thank you so much for the reply! Using this solution produced -Inf for matrix positions where the nucleotide frequency was 0. Using toPWM on an integer matrix that contains 0s does not give this result, but I can't quite figure out what its doing to avoid this.

Thank you again for your help!

**Comment by ge11232002** [comment]
When you have true PFM (with integer inside), a pseudocount is added to each value and then converted to frequency and then log-scale weight. So you will never have the exact 0, which will lead to -Inf after log. Since you only have the fraction, I would suggest to add a small fraction to the matrix and scale by column so the colSum is still 1.

**Comment by erin-a-clark** [comment]
Thank you!
