### ISSUE TITLE
Problem installing TFBSTools

### ISSUE THREAD

**Issue by eudoraleer** [ge11232002/TFBSTools#27]
Hi,

I am trying to install the package but failed:

Creating a new generic function for ‘seqLogo’ in package ‘TFBSTools’
Error in setIs(class2, cli, extensionObject = obji, doComplete = FALSE,  : 
  class “PFMatrixList” cannot extend class “Vector”: slot in class “PFMatrixList” must extend corresponding slot in class “Vector”: fails for elementMetadata
Error in setClass("PFMatrixList", contains = "SimpleList", representation(),  : 
  error in contained classes ("SimpleList") for class “PFMatrixList”; class definition removed from ‘TFBSTools’
Error: unable to load R code in package ‘TFBSTools’
Execution halted
ERROR: lazy loading failed for package ‘TFBSTools’

Please assist me with this, thank you.

**Comment by ge11232002** [comment]
Can you give `sessionInfo()`? The installation seems fine on Bioconductor check: http://bioconductor.org/checkResults/3.13/bioc-LATEST/TFBSTools/

**Comment by eudoraleer** [comment]
> Can you give `sessionInfo()`? The installation seems fine on Bioconductor check: http://bioconductor.org/checkResults/3.13/bioc-LATEST/TFBSTools/

Hi! Thank you for your quick reply. The problem has been solved after I installed the newest R version, thank you anyways!!:D
