### ISSUE TITLE
getMatrixSet

### ISSUE THREAD

**Issue by chrismahony** [ge11232002/TFBSTools#28]
I have tried to run :

pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 7955, all_versions = FALSE)
)

as my organism is zebrafish I have put the taxID as 7955. When I do this an empty matrix is made. If I chnage the taxID to human, it works fine.

Can you tell me how I can use this for zebrafish?

Thanks
Chris

**Comment by ge11232002** [comment]
Because we don't have zebrafish collection on JASPAR.
