### ISSUE TITLE
get alignment/gap position from PFMSimilarity

### ISSUE THREAD

**Issue by fgeier** [ge11232002/TFBSTools#30]
Dear Ge,

as a feature request, could you also output the optimal alignment position and gap position(s) in `PFMSimilarity`? This would really help when visualizing the aligned motifs in e.g. a motif stack.  

Best, Florian

**Comment by ge11232002** [comment]
Dear Florian,

Unfortunately for now I don't have time to expand this package. I recommend to use https://meme-suite.org/meme/tools/tomtom for motif comparison.

Best,
Ge
