### ISSUE TITLE
JASPAR 2022

### ISSUE THREAD

**Issue by akhst7** [ge11232002/TFBSTools#32]
Hi, 

JASPAR 2022 DB is out.  Could you add the JASPAR 2022 release ? 

Thanks.

**Comment by ge11232002** [comment]
Hi, I am no longer in the lab and don't have the JASPAR 2022 copy. I though it was uploaded to Bioconductor. @da-bar  Did you do it?

**Comment by da-bar** [comment]
Hi @akhst7 ,
JASPAR2022, unfortunately, didn't make it to Bioconductor yet, however, it can be installed from here:
https://github.com/da-bar/JASPAR2022

**Comment by akhst7** [comment]
Thanks, guys !!
