### ISSUE TITLE
runMEME fails

### ISSUE THREAD

**Issue by ge11232002** [ge11232002/TFBSTools#4]
> motifSet <- runMEME(file.path(system.file("extdata",
+                                           package="TFBSTools"), "crp0.s"),
+                     binary="meme",
+                     arguments=list("-nmotifs"=3)
+                    )
meme /usr/local/lib/R/site-library/TFBSTools/extdata/crp0.s -text -dna -nmotifs 3  2>/dev/null
Error in seq.default(from = indexNames[i] + 4, to = indexNames[i] + 4 +  :
  'to' cannot be NA, NaN or infinite
In addition: Warning messages:
1: In run_MEME(x, binary = binary, seqtype = seqtype, arguments = arguments) :
  NAs introduced by coercion
2: In run_MEME(x, binary = binary, seqtype = seqtype, arguments = arguments) :
  NAs introduced by coercion
3: In run_MEME(x, binary = binary, seqtype = seqtype, arguments = arguments) :
  NAs introduced by coercion
> motifSet
Error: object 'motifSet' not found

**Comment by ge11232002** [comment]
closed via f08c1575fcd203acd02d399a5392b1660f0c08e1

**Comment by PietaSchofield** [comment]
Hullo

I am experiencing this issue which I notice you have fixed. I am running the TFBSTools_1.8.2 devtools_1.10.0 which I installed from Bioconductor. I have attempted to install the code from GitHub but get a message about the wrong version of S4Vectors when I attempt that. Should it be possible to install the GitHub version on the current R3.2.4 release or do I need to be running a development version of R?

Many thanks

Pieta

**Comment by ge11232002** [comment]
I updated the release branch. The change will take some time to appear in Bioconductor. But you can see the changes from https://github.com/Bioconductor-mirror/TFBSTools and install with 
```R
devtools::install_github("Bioconductor-mirror/TFBSTools", ref="b12485a308b49db53982a86caca193ed1bf45693")
```
