### ISSUE TITLE
loading TFBSTools

### ISSUE THREAD

**Issue by xszomol** [ge11232002/TFBSTools#5]
I have R version 3.0, I installed TFBSTools 1.9.11 however I am not able to load the library. 
I get this error:

> library(TFBSTools)

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/DirichletMultinomial/libs/DirichletMultinomial.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/DirichletMultinomial/libs/DirichletMultinomial.so, 6): Library not loaded: /usr/local/lib/libgsl.0.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/DirichletMultinomial/libs/DirichletMultinomial.so
  Reason: image not found
Error: package or namespace load failed for ‘TFBSTools’

**Comment by ge11232002** [comment]
It's the problem of another Biocondutor `DirichletMultinomial` which `TFBSTools` depends on. You have `DirichletMultinomial` successfully installed? Can you do `library(DirichletMultinomial)`? Do you have `gsl` C library installed?
