### ISSUE TITLE
wrapper issue: integer arguments converted to character

### ISSUE THREAD

**Issue by balwierz** [ge11232002/TFBSTools#7]
`runMEME(x=thisPromSeq[1:500], arguments=list("-nmotifs"=5, "-minw"=5, "-maxw"=14, "-maxsize"=200000, "-p"=8))`

results in:

`meme /tmp/RtmpNvNJvR/MEME_805378c037d6.fasta -text -dna -nmotifs 5 -minw 5 -maxw 14 -maxsize **2e+05** -p 8  2>/dev/null`

**Comment by ge11232002** [comment]
Fix via db41a79e23d55b41c963d32e5ff70fa2a6d99a9c.
Closed.
